### ISSUE TITLE
Allow automatic Pre-defined excel sheet input for PDF/XFA files

### ISSUE THREAD

**Issue by ghost** [Staubteufel/BulkPDF#15]
I love this program and am relatively new to coding!

The program currently requires the user to select the columns associated with the fields on the PDF/XFA forms.

If the excel spreadsheet provided has the form Field Names pre-populated in the column header, it would be a great opportunity to skip the user input and automatically assign the columns to their respective input field.

**Comment by Tadelsucht** [comment]
I don't think so, because the forms the user populate are mostly wired by naming the input field ("Input_Text_1" etc.).
For the most users the first configuration for a new pdf forumlar is a real guessing game. Same for checkboxes: https://github.com/Tadelsucht/BulkPDF/issues/4

If you like you can add this feature.
