### ISSUE TITLE
Turkish characters

### ISSUE THREAD

**Issue by Alacritas1** [Staubteufel/BulkPDF#21]
Hello,

When I try to fill pdf files with Turkish text some Turkish characters don't appear on the output. 
And when I enable unicode setting, characters appear but the text font changes.

Am i doing something wrong or is there no way to use this software properly with Turkish characters at this moment?

Any help would be greatly appreciated. Thanks in advance.

and teşekkürler.

![image](https://user-images.githubusercontent.com/70648645/113819812-818d5d00-9782-11eb-8566-0449c9bd1a46.png)
![image](https://user-images.githubusercontent.com/70648645/113819827-87833e00-9782-11eb-8ca3-a64952c1d26f.png)

**Comment by Tadelsucht** [comment]
Hello, 

the support of unicode characters is a two weeks old new feature.
This behavior is a problem which I am, at least now, not able to fix. The cause is a problem with writing text fonts. The library which I use, writes by default in the PDF forms with the arial windows font which is not capable of displaying characters like chinese, cyrillic or turkish ones. Cause of this, I added a free font to this programm, which support all these letters and is then embedded in the pdf output file  (You may notice the increasing size of the pdf file ~3MB of font data) and looks a little bit odd (but hey it's free).

Maybe I will find a solution for this font selection in the future, but for now that's all the programm is able to.

**Comment by Alacritas1** [comment]
Hey,

I found a relatively simple work-around.

I just replaced the unifont.ttf with the font I wanted and renamed it unifont.ttf then selected unicode in the options. Perfect result.

Just letting you know.

Thanks for the awesomely simple program.

**Comment by Tadelsucht** [comment]
Great idea!

In the next release I will add support for GUI selection of the ttf file :)
