### ISSUE TITLE
Wrong document format for OpenDocument-Spreadsheets

### ISSUE THREAD

**Issue by PeaaZee** [Staubteufel/BulkPDF#22]
Hello,

I downloaded the portable version of BulkPDF 1.2.3.0 and I realised that the "open spreadsheet"-Window uses the wrong document format. The open document standard uses .ods for its spreadsheets. BulkPDF looks for .odc.

![grafik](https://user-images.githubusercontent.com/66795669/115578936-ffdf1880-a2c5-11eb-9aa5-b0ffb2b4f885.png)

See: https://en.wikipedia.org/wiki/OpenDocument_technical_specification#Documents

Kind regards

**Comment by Tadelsucht** [comment]
Thank your for your issue. I have now noticed that the program is not capable to open .odc files, because the underlying spreadsheet library doesn't support it. In the next version the *.odc filter entry will be removed.

https://github.com/Tadelsucht/BulkPDF/commit/0cdbf53d4b7d1148a2941ec9ff80b0040f21f95c
